name:                ad-alta-voce
version:             0.0.0.1
github:              "norangebit/ad-alta-voce"
license:             GPL-3
author:              "Raffaele Mignone"
maintainer:          "git@norangeb.it"
copyright:           "2021 norangebit"

extra-source-files:
- README.md
- ChangeLog.md

data-dir: data
data-files: 
- templates/podcast.mustache

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Script per la generazione dei Feed Podcast di Ad Alta Voce       

dependencies:
- base >= 4.7 && < 5
- directory
- text
- time
- scalpel
- mustache
- parsec
- optparse-applicative

library:
  source-dirs: src

executables:
  loud:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ad-alta-voce

tests:
  ad-alta-voce-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ad-alta-voce
